TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-a
TARGET_CPU_ABI := arm64-v8a
TARGET_CPU_ABI2 :=
TARGET_CPU_VARIANT := generic

TARGET_2ND_ARCH := arm
TARGET_2ND_ARCH_VARIANT := armv8-a
TARGET_2ND_CPU_ABI := armeabi-v7a
TARGET_2ND_CPU_ABI2 := armeabi
TARGET_2ND_CPU_VARIANT := generic

BOARD_KERNEL_BASE := 0x00000000
BOARD_KERNEL_PAGESIZE := 4096

BOARD_USES_RECOVERY_AS_BOOT := true
BOARD_HAS_NO_RECOVERY_PARTITION := true
TARGET_NO_RECOVERY := true

TW_INCLUDE_REPACKTOOLS := true
TW_CRYPTO_USE_SYSTEM_VOLD := true

