$(call inherit-product, $(SRC_TARGET_DIR)/product/aosp_base.mk)

PRODUCT_NAME := omni_RMX5060
PRODUCT_DEVICE := RMX5060
PRODUCT_BRAND := realme
PRODUCT_MODEL := Realme Neo7
PRODUCT_MANUFACTURER := realme

TW_THEME := portrait_hdpi
RECOVERY_SDCARD_ON_DATA := true
TW_INCLUDE_CRYPTO := true
TW_INCLUDE_CRYPTO_FBE := true
TW_INCLUDE_FBE_METADATA_DECRYPT := true
BOARD_USES_METADATA_PARTITION := true
TW_EXCLUDE_DEFAULT_USB_INIT := true
TW_HAS_NO_RECOVERY_PARTITION := true
TARGET_COPY_OUT_VENDOR := vendor

